project_id = "vgddrhyjttyrathqhefb"

[db]
major_version = 15

[analytics]
enabled = false

[auth]
enable_signup = true

[auth.email]
enable_signup = true

[functions.calendar-ics]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false
